[package]
name = "network_analysis"
version = "0.1.0"
edition = "2021"

[dependencies]
csv = "1.1"
petgraph = "0.6"
serde = { version = "1.0", features = ["derive"] }
ndarray = "0.15"
rustworkx-core = "0.15.1"
